### ISSUE TITLE
Crash when attempting to display "Engineer's Manual"

### ISSUE THREAD

**Issue by niraqw** [Astavie/BookDisplay#3]
Trying to display the "Engineer's Manual" from Immersive Engineering crashes the game.

Minecraft: 1.16.5
Forge: 36.1.16
Book Display: 2.0.0
Immersive Engineering: 4.2.4-134

Here's the crash report:

java.lang.NoSuchMethodError: blusunrize.immersiveengineering.api.ManualHelper.getManual()Lblusunrize/lib/manual/ManualInstance;
	at astavie.bookdisplay.wrapper.immersiveengineering.IEWrapper.<init>(IEWrapper.java:13) ~[bookdisplay:1.16.5-2.0.0] {re:classloading}
	at astavie.bookdisplay.wrapper.immersiveengineering.IEWrapper.lambda$register$1(IEWrapper.java:17) ~[bookdisplay:1.16.5-2.0.0] {re:classloading}
	at astavie.bookdisplay.BookDisplay.find(BookDisplay.java:57) ~[bookdisplay:1.16.5-2.0.0] {re:classloading}
	at astavie.bookdisplay.EventHandler.mainhand(EventHandler.java:37) ~[bookdisplay:1.16.5-2.0.0] {re:classloading}
	at astavie.bookdisplay.EventHandler.enable(EventHandler.java:107) ~[bookdisplay:1.16.5-2.0.0] {re:classloading}
	at astavie.bookdisplay.EventHandler.onKey(EventHandler.java:75) ~[bookdisplay:1.16.5-2.0.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_90_EventHandler_onKey_KeyInputEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.fireKeyInput(ForgeHooksClient.java:738) ~[forge:?] {re:classloading}
	at net.minecraft.client.KeyboardListener.func_197961_a(KeyboardListener.java:356) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardListener.func_228003_c_(KeyboardListener.java:391) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.KeyboardListener.func_228001_b_(KeyboardListener.java:390) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:305) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.16.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

**Comment by Astavie** [comment]
This issue is not reproducible on my end. What are all the mods you are using?

**Comment by niraqw** [comment]
I made a fresh instance with just Book Display and Immersive Engineering to make sure that no other mods were causing the crash. It seems that the issue does not occur with ImmersiveEngineering-1.16.5-5.0.0-135, only earlier versions.
